server:
  port: 1015
  servlet:
    context-path: /gm
spring:
  datasource:
    #url: jdbc:mysql://127.0.0.1/shiro?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://106.54.114.18:3306/gm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gm
    password: Gmmg;123
mybatis:
  type-aliases-package: com.gm.pojo
  mapper-locations:       
  - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名规则    last_name 可以映射为 lastName
logging:
  level:
    com.gm: debug